#!/usr/bin/env node
/**
 * Regenerates the token inventory block in AGENTS.md from src/app/globals.css.
 *
 * Token *names* change every time globals.css changes; what each family *means*
 * does not. This script owns the names so the hand-written semantics in AGENTS.md
 * stay the only part a human maintains.
 *
 *   node scripts/sync-tokens.mjs           rewrite the block
 *   node scripts/sync-tokens.mjs --check   exit 1 if the block is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const CSS_PATH = join(ROOT, "src/app/globals.css");
export const DOC_PATH = join(ROOT, "AGENTS.md");

const BEGIN = "<!-- BEGIN:generated-tokens -->";
const END = "<!-- END:generated-tokens -->";

/**
 * `selector` is anchored to the start of a line so that `.dark` matches the rule
 * and not the `@custom-variant dark (&:is(.dark *))` declaration above it.
 */
function ruleBody(css, selector) {
  const at = css.search(
    new RegExp(`^${selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{`, "m")
  );
  if (at === -1) throw new Error(`No \`${selector}\` rule in globals.css`);
  const open = css.indexOf("{", at);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`Unterminated \`${selector}\` rule in globals.css`);
}

function declarations(body) {
  const decls = new Map();
  const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const [, name, value] of withoutComments.matchAll(
    /(--[\w-]+)\s*:\s*([^;]+);/g
  )) {
    decls.set(name, value.trim());
  }
  return decls;
}

export function readTokens() {
  const css = readFileSync(CSS_PATH, "utf8");
  const theme = declarations(ruleBody(css, "@theme inline"));
  const light = declarations(ruleBody(css, ":root"));
  const dark = declarations(ruleBody(css, ".dark"));

  const groups = { color: [], radius: [], shadow: [], text: [], font: [] };

  for (const name of theme.keys()) {
    if (name.startsWith("--color-")) groups.color.push(name.slice(8));
    else if (name.startsWith("--radius-")) groups.radius.push(name.slice(9));
    else if (name.startsWith("--shadow-")) groups.shadow.push(name.slice(9));
    else if (name.startsWith("--font-")) groups.font.push(name.slice(7));
    else if (name.startsWith("--text-") && !name.slice(7).includes("--")) {
      groups.text.push(name.slice(7));
    }
  }

  for (const list of Object.values(groups)) list.sort();
  return { theme, light, dark, groups };
}

/**
 * Rule 4 ("all colors support both modes") made machine-checkable: every
 * `--color-*` that aliases a variable must resolve in `:root` *and* `.dark`.
 */
export function findModeGaps({ theme, light, dark }) {
  const gaps = [];
  for (const [name, value] of theme) {
    if (!name.startsWith("--color-")) continue;
    const alias = value.match(/^var\((--[\w-]+)\)$/)?.[1];
    if (!alias) continue;
    const missing = [
      !light.has(alias) && ":root",
      !dark.has(alias) && ".dark",
    ].filter(Boolean);
    if (missing.length) gaps.push({ token: name, alias, missing });
  }
  return gaps;
}

const list = (names) => names.map((n) => `\`${n}\``).join(" · ");

export function renderBlock(tokens = readTokens()) {
  const { groups } = tokens;
  return [
    BEGIN,
    "<!-- Generated by `npm run sync:tokens` from src/app/globals.css. Do not edit by hand. -->",
    "",
    `**Color** (${groups.color.length}) — use as \`bg-*\`, \`text-*\`, \`border-*\`, \`ring-*\`, \`fill-*\`, \`stroke-*\`.`,
    "",
    list(groups.color),
    "",
    `**Radius** (${groups.radius.length}) — use as \`rounded-*\`.`,
    "",
    list(groups.radius),
    "",
    `**Elevation** (${groups.shadow.length}) — use as \`shadow-*\`.`,
    "",
    list(groups.shadow),
    "",
    `**Type scale** (${groups.text.length}) — use as \`text-*\`.`,
    "",
    list(groups.text),
    "",
    `**Font** (${groups.font.length}) — use as \`font-*\`.`,
    "",
    list(groups.font),
    "",
    END,
  ].join("\n");
}

export function currentDoc() {
  return readFileSync(DOC_PATH, "utf8");
}

/** Swap the content between a `BEGIN:` / `END:` marker pair, markers included. */
export function replaceBlock(doc, name, body) {
  const begin = `<!-- BEGIN:${name} -->`;
  const end = `<!-- END:${name} -->`;
  const start = doc.indexOf(begin);
  const stop = doc.indexOf(end);
  if (start === -1 || stop === -1) {
    throw new Error(`Missing the ${begin} / ${end} markers`);
  }
  return doc.slice(0, start) + body + doc.slice(stop + end.length);
}

export function withBlock(doc, block) {
  return replaceBlock(doc, "generated-tokens", block);
}

function main() {
  const check = process.argv.includes("--check");
  const tokens = readTokens();
  const doc = currentDoc();
  const next = withBlock(doc, renderBlock(tokens));

  const gaps = findModeGaps(tokens);
  for (const { token, alias, missing } of gaps) {
    console.error(
      `warning: ${token} → ${alias} is not defined in ${missing.join(" or ")}`
    );
  }

  if (next === doc) {
    console.log("Token block is up to date.");
    return;
  }
  if (check) {
    console.error(
      "Token block in AGENTS.md is stale. Run `npm run sync:tokens`."
    );
    process.exit(1);
  }
  writeFileSync(DOC_PATH, next);
  const total = Object.values(tokens.groups).reduce((n, g) => n + g.length, 0);
  console.log(`Wrote ${total} tokens to AGENTS.md.`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
